### ISSUE TITLE
Invalid Entity ID in train.json

### ISSUE THREAD

**Issue by bohuizhang** [lm-kbc/dataset2023#1]
Dear Organizers,

There is an invalid (maybe outdated) entity ID, `Q16862766` (Word & Void) that cannot be queried through Wikidata SPARQL. It has been redirected to the new ID `Q8034285`. Could you please update it if it is OK?

Regards,

Bohui

**Comment by srazniewski** [comment]
Thanks for pointing out, we have replaced the merged ID with the new redirect target.
